openapi: 3.0.3
info:
  title: Auction Marketplace API
  version: 1.0.0
  description: Backend Assessment
paths:
  /api/auctions/:
    get:
      operationId: auctions_list
      description: List active auction listings or create a new auction.
      summary: List auctions
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - Auctions
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedAuctionListList'
          description: ''
    post:
      operationId: auctions_create
      description: List active auction listings or create a new auction.
      summary: Create auction
      tags:
      - Auctions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuctionCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuctionCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuctionCreate'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuctionList'
          description: ''
  /api/auctions/{id}/:
    get:
      operationId: auctions_retrieve
      summary: Retrieve auction
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Auctions
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuctionDetail'
          description: ''
    put:
      operationId: auctions_update
      summary: Update auction
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Auctions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuctionUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuctionUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuctionUpdate'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuctionDetail'
          description: ''
    patch:
      operationId: auctions_partial_update
      summary: Partially update auction
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Auctions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedAuctionUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedAuctionUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedAuctionUpdate'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuctionDetail'
          description: ''
    delete:
      operationId: auctions_destroy
      summary: Delete auction
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Auctions
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/auctions/{id}/complete/:
    post:
      operationId: auctions_complete_create
      description: Mark an auction as completed and assign the highest bidder as winner.
      summary: Complete auction
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Auctions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompleteAuctionResponse'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CompleteAuctionResponse'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CompleteAuctionResponse'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompleteAuctionResponse'
          description: ''
  /api/auth/login/:
    post:
      operationId: auth_login_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/auth/logout/:
    post:
      operationId: auth_logout_create
      description: Blacklist refresh token and logout user.
      summary: Logout
      tags:
      - Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Logout'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Logout'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Logout'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutResponse'
          description: ''
  /api/auth/refresh/:
    post:
      operationId: auth_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/auth/register/:
    post:
      operationId: auth_register_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
          description: ''
  /api/bids/{auction_id}/bids/:
    post:
      operationId: bids_bids_create
      summary: Place bid
      parameters:
      - in: path
        name: auction_id
        schema:
          type: integer
        required: true
      tags:
      - Bids
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BidCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BidCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BidCreate'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BidDetail'
          description: ''
  /api/bids/{auction_id}/bids/history/:
    get:
      operationId: bids_bids_history_list
      description: Return paginated bid history for an auction.
      summary: List bid history
      parameters:
      - in: path
        name: auction_id
        schema:
          type: integer
        required: true
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - Bids
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedBidDetailList'
          description: ''
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - ht
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    AuctionCreate:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
        description:
          type: string
        starting_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,10}(?:\.\d{0,2})?$
        end_time:
          type: string
          format: date-time
      required:
      - description
      - end_time
      - starting_price
      - title
    AuctionDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        description:
          type: string
        starting_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,10}(?:\.\d{0,2})?$
        current_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,10}(?:\.\d{0,2})?$
        status:
          $ref: '#/components/schemas/StatusEnum'
        end_time:
          type: string
          format: date-time
        owner:
          type: string
          readOnly: true
        winner:
          type: string
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - current_price
      - description
      - end_time
      - id
      - owner
      - starting_price
      - title
      - updated_at
      - winner
    AuctionList:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        current_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,10}(?:\.\d{0,2})?$
        status:
          $ref: '#/components/schemas/StatusEnum'
        end_time:
          type: string
          format: date-time
        owner:
          type: string
          readOnly: true
      required:
      - current_price
      - end_time
      - id
      - owner
      - title
    AuctionUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
        description:
          type: string
        end_time:
          type: string
          format: date-time
    BidCreate:
      type: object
      properties:
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,10}(?:\.\d{0,2})?$
      required:
      - amount
    BidDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        bidder:
          type: string
          readOnly: true
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,10}(?:\.\d{0,2})?$
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - amount
      - bidder
      - created_at
      - id
    CompleteAuctionResponse:
      type: object
      properties:
        message:
          type: string
      required:
      - message
    Logout:
      type: object
      properties:
        refresh:
          type: string
      required:
      - refresh
    LogoutResponse:
      type: object
      properties:
        message:
          type: string
      required:
      - message
    PaginatedAuctionListList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/AuctionList'
    PaginatedBidDetailList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/BidDetail'
    PatchedAuctionUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
        description:
          type: string
        end_time:
          type: string
          format: date-time
    Register:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        password:
          type: string
          writeOnly: true
          minLength: 8
      required:
      - password
      - username
    StatusEnum:
      enum:
      - ACTIVE
      - COMPLETED
      - CANCELLED
      type: string
      description: |-
        * `ACTIVE` - Active
        * `COMPLETED` - Completed
        * `CANCELLED` - Cancelled
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
